// Comprehensive list of Albion Online items for Market Flipper

const TIERS = ['T4', 'T5', 'T6', 'T7', 'T8'];

const WEAPON_TYPES = [
  // Swords
  'MAIN_SWORD', '2H_CLAYMORE', '2H_DUALSWORD', 'MAIN_SCIMITAR', '2H_CLEAVER_HELL', '2H_CLAYMORE_AVALON',
  // Axes
  'MAIN_AXE', '2H_HALBERD', '2H_AXE', '2H_SCYTHE_HELL', '2H_AXE_AVALON',
  // Maces
  'MAIN_MACE', '2H_MACE', '2H_FLAIL', 'MAIN_ROCKMACE_KEEPER', '2H_MACE_MORGANA',
  // Hammers
  'MAIN_HAMMER', '2H_POLEHAMMER', '2H_HAMMER', '2H_HAMMER_UNDEAD', '2H_RAM_KEEPER',
  // Crossbows
  '2H_CROSSBOW', '2H_CROSSBOWLARGE', 'MAIN_1HCROSSBOW', '2H_REPEATINGCROSSBOW_UNDEAD',
  // Bows
  '2H_BOW', '2H_WARBOW', '2H_LONGBOW', '2H_BOW_HELL', '2H_BOW_KEEPER',
  // Spears
  'MAIN_SPEAR', '2H_SPEAR', '2H_GLAIVE', 'MAIN_SPEAR_KEEPER', '2H_HARPOON_HELL',
  // Daggers
  'MAIN_DAGGER', '2H_DAGGERPAIR', '2H_CLAWPAIR', 'MAIN_RAPIER_MORGANA', '2H_IRONGAUNTLETS_HELL',
  // Staffs
  'MAIN_FIRESTAFF', '2H_FIRESTAFF', '2H_INFERNOSTAFF',
  'MAIN_HOLYSTAFF', '2H_HOLYSTAFF', '2H_DIVINESTAFF',
  'MAIN_NATURESTAFF', '2H_NATURESTAFF', '2H_WILDSTAFF',
  'MAIN_CURSEDSTAFF', '2H_CURSEDSTAFF', '2H_DEMONICSTAFF',
  'MAIN_ARCANESTAFF', '2H_ARCANESTAFF', '2H_ENIGMATICSTAFF',
  'MAIN_FROSTSTAFF', '2H_FROSTSTAFF', '2H_GLACIALSTAFF'
];

const ARMOR_TYPES = [
  // Plate
  'HEAD_PLATE_SET1', 'ARMOR_PLATE_SET1', 'SHOES_PLATE_SET1',
  'HEAD_PLATE_SET2', 'ARMOR_PLATE_SET2', 'SHOES_PLATE_SET2',
  'HEAD_PLATE_SET3', 'ARMOR_PLATE_SET3', 'SHOES_PLATE_SET3',
  // Leather
  'HEAD_LEATHER_SET1', 'ARMOR_LEATHER_SET1', 'SHOES_LEATHER_SET1',
  'HEAD_LEATHER_SET2', 'ARMOR_LEATHER_SET2', 'SHOES_LEATHER_SET2',
  'HEAD_LEATHER_SET3', 'ARMOR_LEATHER_SET3', 'SHOES_LEATHER_SET3',
  // Cloth
  'HEAD_CLOTH_SET1', 'ARMOR_CLOTH_SET1', 'SHOES_CLOTH_SET1',
  'HEAD_CLOTH_SET2', 'ARMOR_CLOTH_SET2', 'SHOES_CLOTH_SET2',
  'HEAD_CLOTH_SET3', 'ARMOR_CLOTH_SET3', 'SHOES_CLOTH_SET3',
];

const ACCESSORY_TYPES = [
  'BAG', 'CAPE'
];

// Helper to generate IDs
const generateIds = (types: string[]) => {
  const ids: string[] = [];
  TIERS.forEach(tier => {
    types.forEach(type => {
      ids.push(`${tier}_${type}`);
    });
  });
  return ids;
};

export const ITEM_CATEGORIES = {
  'Popular': [
    // Bags
    'T4_BAG', 'T5_BAG', 'T6_BAG', 'T7_BAG', 'T8_BAG',
    // Capes
    'T4_CAPE', 'T5_CAPE', 'T6_CAPE', 'T7_CAPE', 'T8_CAPE',
    // Popular Weapons
    'T4_MAIN_SWORD', 'T6_MAIN_SWORD', 'T8_MAIN_SWORD',
    'T4_2H_CLAYMORE', 'T6_2H_CLAYMORE', 'T8_2H_CLAYMORE',
    'T4_2H_BOW', 'T6_2H_BOW', 'T8_2H_BOW',
    'T4_MAIN_FIRESTAFF', 'T6_MAIN_FIRESTAFF', 'T8_MAIN_FIRESTAFF',
    // Popular Armor
    'T4_ARMOR_PLATE_SET1', 'T6_ARMOR_PLATE_SET1', 'T8_ARMOR_PLATE_SET1',
    'T4_ARMOR_CLOTH_SET1', 'T6_ARMOR_CLOTH_SET1', 'T8_ARMOR_CLOTH_SET1',
    'T4_ARMOR_LEATHER_SET1', 'T6_ARMOR_LEATHER_SET1', 'T8_ARMOR_LEATHER_SET1',
  ],
  'Melee Weapons': generateIds([
    'MAIN_SWORD', '2H_CLAYMORE', '2H_DUALSWORD', 
    'MAIN_AXE', '2H_HALBERD', '2H_AXE',
    'MAIN_MACE', '2H_MACE', 'MAIN_HAMMER', '2H_HAMMER',
    'MAIN_DAGGER', '2H_DAGGERPAIR', '2H_CLAWPAIR',
    'MAIN_SPEAR', '2H_SPEAR', '2H_GLAIVE'
  ]),
  'Ranged/Magic': generateIds([
    '2H_BOW', '2H_WARBOW', '2H_LONGBOW',
    '2H_CROSSBOW', 'MAIN_1HCROSSBOW',
    'MAIN_FIRESTAFF', '2H_FIRESTAFF',
    'MAIN_HOLYSTAFF', '2H_HOLYSTAFF',
    'MAIN_NATURESTAFF', '2H_NATURESTAFF',
    'MAIN_CURSEDSTAFF', '2H_CURSEDSTAFF',
    'MAIN_ARCANESTAFF', '2H_ARCANESTAFF',
    'MAIN_FROSTSTAFF', '2H_FROSTSTAFF'
  ]),
  'Armor (Plate)': generateIds(['HEAD_PLATE_SET1', 'ARMOR_PLATE_SET1', 'SHOES_PLATE_SET1', 'HEAD_PLATE_SET2', 'ARMOR_PLATE_SET2', 'SHOES_PLATE_SET2', 'HEAD_PLATE_SET3', 'ARMOR_PLATE_SET3', 'SHOES_PLATE_SET3']),
  'Armor (Leather)': generateIds(['HEAD_LEATHER_SET1', 'ARMOR_LEATHER_SET1', 'SHOES_LEATHER_SET1', 'HEAD_LEATHER_SET2', 'ARMOR_LEATHER_SET2', 'SHOES_LEATHER_SET2', 'HEAD_LEATHER_SET3', 'ARMOR_LEATHER_SET3', 'SHOES_LEATHER_SET3']),
  'Armor (Cloth)': generateIds(['HEAD_CLOTH_SET1', 'ARMOR_CLOTH_SET1', 'SHOES_CLOTH_SET1', 'HEAD_CLOTH_SET2', 'ARMOR_CLOTH_SET2', 'SHOES_CLOTH_SET2', 'HEAD_CLOTH_SET3', 'ARMOR_CLOTH_SET3', 'SHOES_CLOTH_SET3']),
  'Accessories': generateIds(['BAG', 'CAPE']),
  'Artifact Weapons': generateIds([
    'MAIN_SCIMITAR', '2H_CLEAVER_HELL', '2H_CLAYMORE_AVALON',
    '2H_SCYTHE_HELL', '2H_AXE_AVALON',
    'MAIN_ROCKMACE_KEEPER', '2H_MACE_MORGANA',
    '2H_HAMMER_UNDEAD', '2H_RAM_KEEPER',
    '2H_REPEATINGCROSSBOW_UNDEAD',
    '2H_BOW_HELL', '2H_BOW_KEEPER',
    'MAIN_SPEAR_KEEPER', '2H_HARPOON_HELL',
    'MAIN_RAPIER_MORGANA', '2H_IRONGAUNTLETS_HELL',
    '2H_INFERNOSTAFF', '2H_DIVINESTAFF', '2H_WILDSTAFF', '2H_DEMONICSTAFF', '2H_ENIGMATICSTAFF', '2H_GLACIALSTAFF'
  ])
};
